### ISSUE TITLE
Review del desafío

### ISSUE THREAD

**Issue by tobiasfacello** [NicolasStebner/apx-desafio-m3#1]
Hola Nico, felicidades por haber llegado al desafío final 🚀
Tengo un par de cosas para comentarte respecto al desafío, cosas las cuales me parecen necesarias para la aprobación del mismo.

- **Uso de medidas fijas vs medidas relativas**
![image](https://user-images.githubusercontent.com/69740939/189468507-074a0d12-3604-485f-a81f-d0f1ea07e3f1.png)
![image](https://user-images.githubusercontent.com/69740939/189468627-a019469a-469d-46aa-9ca7-07c4b7d02cc1.png)

Como te darás cuenta en estas imagenes, cuando uno "juega" con el ancho del viewport (es decir, el ancho total de la ventana) los contenedores (y sus respectivos elementos) tienden a romperse a medida que uno varía en cuanto a las medidas.
Una de las razones es la que destaqué al principio, que es el uso de medidas fijas. Como solución a esto te propongo hacer uso de medidas relativas (como por ejemplo **porcentajes**), ya que estas unidades de medida van variando a medida que el ancho o alto de un dispositivo cambia.
⚠️ Esto no quiere decir que el uso de medidas fijas sea un error, pero sí hay que tener en cuenta qué tipo de medida aplica mejor en cada caso, sobre todo para despreocuparse de estas cuestiones.

Una vez puedas resolver eso, creo que va a estar bien como para ser aprobado sin más que agregar. Desde ya mucho éxito con esa corrección y cualquier pregunta que tengas no dudes en volcarla en el canal de Discord correspondiente. Éxitos! 💪🏼

**Comment by gonzaliski** [comment]
Hola Tobi, disculpá que moleste por acá jeje. Me parece que Nico pudo resolverlo toqueteando las media query. Según revisé, las medidas relativas se ven a mitad del modulo 4!

**Comment by tobiasfacello** [comment]
Hola @gonzaliski ! Pero por favor, jamás es una molesita... Gracias por la revisión del contenido la verdad no tenía en cuenta esa diferencia, creía que se veía todo de primera y ya se empleaba a gusto de uno. Así que gracias por estar al pendiente de eso! 🚀
